version: "2.1"

services:
  api:
    build: ./src
    command: python3 main.py
    ports:
      - "8000:8000"
    env_file: .env.any

  redis:
    image: redis:7.2.3-alpine
    ports:
      - "6379:6379"
    container_name: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping", "|", "grep", "PONG" ]
      interval: 5s
      retries: 5
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15-alpine
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 5s
      retries: 15


volumes:
  postgres_data:
  redis_data:
