name: Python Package
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
        poetry-version:
          - "1.5.1"

    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ matrix.poetry.version }}
          virtualenvs-create: true
          virtualenvs-in-project: false

      - name: Install Dependencies
        run: |
          poetry install & echo "Dependencies installed"

      - name: Run Pytest
        run: |
          poetry run pytest

      - name: Check Github Secret
        run: | 
          echo ${{ secrets.SECRET_KEY }}