name: Run Pytest
on:
  push:
    branches:
      - '**'

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
        poetry-version:
          - "1.5.1"
    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - ${{ secrets.POSTGRES_PORT }}:${{ secrets.POSTGRES_PORT }}
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      redis:
        image: redis:7.2.3-alpine
        ports:
          - ${{ secrets.REDIS_PORT }}:${{ secrets.REDIS_PORT }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Poetry Environment
        uses: snok/install-poetry@v1
        with:
          version: ${{ matrix.poetry-version }}
          virtualenvs-create: true
          virtualenvs-in-project: false

      - name: Install Dependencies
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
        run: |
          cd src/
          poetry run pytest
